/********************************************************************
* src/ControlFrameDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/ControlFrameDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableControlFrameDict();
extern void G__cpp_setup_inheritanceControlFrameDict();
extern void G__cpp_setup_typetableControlFrameDict();
extern void G__cpp_setup_memvarControlFrameDict();
extern void G__cpp_setup_globalControlFrameDict();
extern void G__cpp_setup_memfuncControlFrameDict();
extern void G__cpp_setup_funcControlFrameDict();
extern void G__set_cpp_environmentControlFrameDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/ControlFrame.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ControlFrameDictLN_TClass;
extern G__linked_taginfo G__ControlFrameDictLN_TBuffer;
extern G__linked_taginfo G__ControlFrameDictLN_TMemberInspector;
extern G__linked_taginfo G__ControlFrameDictLN_TObject;
extern G__linked_taginfo G__ControlFrameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ControlFrameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ControlFrameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ControlFrameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ControlFrameDictLN_TQObject;
extern G__linked_taginfo G__ControlFrameDictLN_TGWindow;
extern G__linked_taginfo G__ControlFrameDictLN_TGObject;
extern G__linked_taginfo G__ControlFrameDictLN_TGFrame;
extern G__linked_taginfo G__ControlFrameDictLN_TGCompositeFrame;
extern G__linked_taginfo G__ControlFrameDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ControlFrameDictLN_TGTextButton;
extern G__linked_taginfo G__ControlFrameDictLN_TGMainFrame;
extern G__linked_taginfo G__ControlFrameDictLN_ControlFrame;

/* STUB derived class for protected member access */
